# Generated by Django 6.1 on 2026-09-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_hqvault_branch_vault_balance_fundallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
